### ISSUE TITLE
ValueError: could not convert string to float: '1,154.00'

### ISSUE THREAD

**Issue by somer786** [MuhammadAmir5670/psx-data-reader#2]
While downloading data received error
Command:
indu=stocks('INDU',start=datetime.date(2020,1,1),end=datetime.date(2022,4,16))

Error Message:
ValueError: could not convert string to float: '1,154.00

[PSX Data.zip](https://github.com/MuhammadAmir5670/psx-data-reader/files/8499565/PSX.Data.zip)

**Comment by MuhammadAmir5670** [comment]
Hello @somer786, thanks for highlighting the issue, I appreciate your insights, I will be making a new release for the solution to this error, and do let me know if you encounter any more issues.

**Comment by faizan2266** [comment]
Downloading INDU's Data: 100%|███████████████████████████████████████████████████████| 151/151 [00:24<00:00,  6.21it/s]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [111], in <cell line: 1>()
----> 1 data = stocks("INDU", start=datetime.date(2010, 1, 1), end=datetime.date.today())

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\psx\web.py:54, in DataReader.stocks(self, tickers, start, end)
     51 tickers = [tickers] if isinstance(tickers, str) else tickers
     52 dates = self.daterange(start, end)
---> 54 data = [self.get_psx_data(ticker, dates)[start: end] for ticker in tickers]
     56 if len(data) == 1:
     57     return data[0]

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\psx\web.py:54, in <listcomp>(.0)
     51 tickers = [tickers] if isinstance(tickers, str) else tickers
     52 dates = self.daterange(start, end)
---> 54 data = [self.get_psx_data(ticker, dates)[start: end] for ticker in tickers]
     56 if len(data) == 1:
     57     return data[0]

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\psx\web.py:48, in DataReader.get_psx_data(self, symbol, dates)
     44             progressbar.update(1)
     46     data = [instance for instance in data if isinstance(instance, container)]
---> 48 return self.preprocess(data)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\psx\web.py:111, in DataReader.preprocess(self, data)
    109 # coerce each column type to float
    110 for column in data.columns:
--> 111     data[column] = data[column].astype(np.float64)
    112 return data

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\generic.py:5920, in NDFrame.astype(self, dtype, copy, errors)
   5913     results = [
   5914         self.iloc[:, i].astype(dtype, copy=copy)
   5915         for i in range(len(self.columns))
   5916     ]
   5918 else:
   5919     # else, only a single dtype is given
-> 5920     new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
   5921     return self._constructor(new_data).__finalize__(self, method="astype")
   5923 # GH 33113: handle empty frame or series

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\internals\managers.py:419, in BaseBlockManager.astype(self, dtype, copy, errors)
    418 def astype(self: T, dtype, copy: bool = False, errors: str = "raise") -> T:
--> 419     return self.apply("astype", dtype=dtype, copy=copy, errors=errors)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\internals\managers.py:304, in BaseBlockManager.apply(self, f, align_keys, ignore_failures, **kwargs)
    302         applied = b.apply(f, **kwargs)
    303     else:
--> 304         applied = getattr(b, f)(**kwargs)
    305 except (TypeError, NotImplementedError):
    306     if not ignore_failures:

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\internals\blocks.py:580, in Block.astype(self, dtype, copy, errors)
    562 """
    563 Coerce to the new dtype.
    564 
   (...)
    576 Block
    577 """
    578 values = self.values
--> 580 new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
    582 new_values = maybe_coerce_values(new_values)
    583 newb = self.make_block(new_values)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\dtypes\cast.py:1292, in astype_array_safe(values, dtype, copy, errors)
   1289     dtype = dtype.numpy_dtype
   1291 try:
-> 1292     new_values = astype_array(values, dtype, copy=copy)
   1293 except (ValueError, TypeError):
   1294     # e.g. astype_nansafe can fail on object-dtype of strings
   1295     #  trying to convert to float
   1296     if errors == "ignore":

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\dtypes\cast.py:1237, in astype_array(values, dtype, copy)
   1234     values = values.astype(dtype, copy=copy)
   1236 else:
-> 1237     values = astype_nansafe(values, dtype, copy=copy)
   1239 # in pandas we don't store numpy str dtypes, so convert to object
   1240 if isinstance(dtype, np.dtype) and issubclass(values.dtype.type, str):

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\dtypes\cast.py:1181, in astype_nansafe(arr, dtype, copy, skipna)
   1177     raise ValueError(msg)
   1179 if copy or is_object_dtype(arr.dtype) or is_object_dtype(dtype):
   1180     # Explicit copy, or required since NumPy can't view from / to object.
-> 1181     return arr.astype(dtype, copy=True)
   1183 return arr.astype(dtype, copy=copy)

ValueError: could not convert string to float: '1,026.65'

The issue is still there

**Comment by MuhammadAmir5670** [comment]
Hi Faizan, I appreciate your valuable feedback on this, I made some changes
previously although now it might have been due to some other issue, I'll
definitely debug it and resolved this issue. once again thanks for taking
the time to use this library.

Regards,
Muhammad Amir Abbasi

**Comment by faizan2266** [comment]
Thanks for sharing it with us. Saved me a lot of time!

**Comment by faizan2266** [comment]
If you do end up resolving the issue, have a look at this one too

Downloading POL's Data:  33%|███████████████████▋                                       | 6/18 [00:04<00:08,  1.33it/s]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [72], in <cell line: 1>()
----> 1 data = stocks("POL", start=datetime.date(2021, 1, 1), end=datetime.date.today())

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\psx\web.py:54, in DataReader.stocks(self, tickers, start, end)
     51 tickers = [tickers] if isinstance(tickers, str) else tickers
     52 dates = self.daterange(start, end)
---> 54 data = [self.get_psx_data(ticker, dates)[start: end] for ticker in tickers]
     56 if len(data) == 1:
     57     return data[0]

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\psx\web.py:54, in <listcomp>(.0)
     51 tickers = [tickers] if isinstance(tickers, str) else tickers
     52 dates = self.daterange(start, end)
---> 54 data = [self.get_psx_data(ticker, dates)[start: end] for ticker in tickers]
     56 if len(data) == 1:
     57     return data[0]

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\psx\web.py:43, in DataReader.get_psx_data(self, symbol, dates)
     40         futures.append(executor.submit(self.download, symbol=symbol, date=date))
     42     for future in as_completed(futures):
---> 43         data.append(future.result())
     44         progressbar.update(1)
     46 data = [instance for instance in data if isinstance(instance, container)]

File ~\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py:439, in Future.result(self, timeout)
    437     raise CancelledError()
    438 elif self._state == FINISHED:
--> 439     return self.__get_result()
    441 self._condition.wait(timeout)
    443 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File ~\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py:391, in Future.__get_result(self)
    389 if self._exception:
    390     try:
--> 391         raise self._exception
    392     finally:
    393         # Break a reference cycle with the exception in self._exception
    394         self = None

File ~\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py:58, in _WorkItem.run(self)
     55     return
     57 try:
---> 58     result = self.fn(*self.args, **self.kwargs)
     59 except BaseException as exc:
     60     self.future.set_exception(exc)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\psx\web.py:67, in DataReader.download(self, symbol, date)
     65 with session.post(self.__history, data=post) as response:
     66     data = parser(response.text, features="html.parser")
---> 67     data = self.toframe(data)
     68 return data

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\psx\web.py:83, in DataReader.toframe(self, data)
     80             value = datetime.strptime(value, "%b %d, %Y")
     81         stocks[key].append(value)
---> 83 return pd.DataFrame(stocks, columns=headers).set_index("TIME")

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\util\_decorators.py:311, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    305 if len(args) > num_allow_args:
    306     warnings.warn(
    307         msg.format(arguments=arguments),
    308         FutureWarning,
    309         stacklevel=stacklevel,
    310     )
--> 311 return func(*args, **kwargs)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py:5488, in DataFrame.set_index(self, keys, drop, append, inplace, verify_integrity)
   5485                 missing.append(col)
   5487 if missing:
-> 5488     raise KeyError(f"None of {missing} are in the columns")
   5490 if inplace:
   5491     frame = self

KeyError: "None of ['TIME'] are in the columns"
