### ISSUE TITLE
ValueError:

### ISSUE THREAD

**Issue by nassrkhan** [MuhammadAmir5670/psx-data-reader#5]
sir why this code through an error **"time data '1.72' does not match format '%b %d, %Y'"** and how to resolved it?

**Comment by MuhammadAmir5670** [comment]
## A new release in Progress

![image](https://user-images.githubusercontent.com/62555280/187037410-3070ecff-247d-47d4-af51-3f3b4fb1989d.png)

**Comment by danishmeh** [comment]
I hope this message finds you well. First of all, thank you for building and sharing the psx Python package — it's a great initiative for making Pakistan Stock Exchange data accessible via code.

I'm reaching out because I've encountered a consistent error when trying to fetch stock data using valid PSX tickers (e.g., "SILK" or "PRL"). I’ve attached the exact code and error message below for your reference. I believe this may be related to missing or changed data structure on the PSX website, which is causing the TIME column to be absent from the parsed result.


import datetime
from psx import stocks

# Attempting to fetch data for a valid ticker "SILK"
data = stocks("SILK", start=datetime.date(2020, 1, 1), end=datetime.date.today())
print(data)
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

KeyError: "None of ['TIME'] are in the columns"

File ...\psx\web.py, line 83, in DataReader.toframe
    return pd.DataFrame(stocks, columns=headers).set_index("TIME")

KeyError: "None of ['TIME'] are in the columns"
